export const WEB_UI_HTML = String.raw`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="light">
  <title>ForgeMind 工作台</title>
  <style nonce="forgemind-local">
    :root{--bg:#f2e8d9;--panel:#fffaf2;--panel2:#f8efdf;--line:#dfd0bd;--text:#30291f;--muted:#776a5b;--lime:#697341;--lime2:#647541;--amber:#986326;--red:#b3473c;--blue:#4f6f75;--shadow:0 20px 60px rgba(87,67,42,.12)}
    *{box-sizing:border-box}.hidden{display:none!important}body{margin:0;background:radial-gradient(circle at 72% -20%,rgba(190,157,111,.22),transparent 38%),var(--bg);color:var(--text);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif;min-height:100vh}
    button,input,textarea,select{font:inherit}.app{display:grid;grid-template-columns:260px 1fr;min-height:100vh}.sidebar{border-right:1px solid var(--line);padding:28px 22px;display:flex;flex-direction:column;background:rgba(255,250,242,.9);backdrop-filter:blur(18px);position:sticky;top:0;height:100vh}
    .brand{display:flex;gap:13px;align-items:center}.mark{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:var(--lime);color:#fffaf2;font-weight:900;box-shadow:0 10px 28px rgba(91,103,54,.22)}.brand h1{font-size:17px;margin:0;letter-spacing:.2px}.brand p{margin:3px 0 0;color:var(--muted);font-size:12px}
    .side-label{margin:42px 0 15px;color:#917f6a;font-size:10px;font-weight:800;letter-spacing:1.5px}.pipeline{display:grid;gap:7px}.stage{display:flex;align-items:center;gap:11px;padding:10px 11px;border-radius:10px;color:#817462;font-size:13px;transition:.2s}.stage-dot{width:9px;height:9px;border:1px solid #b4a590;border-radius:50%}.stage.active{background:rgba(111,121,70,.11);color:var(--text)}.stage.active .stage-dot{border-color:var(--lime);background:var(--lime);box-shadow:0 0 0 4px rgba(111,121,70,.14)}.stage.done{color:#645e49}.stage.done .stage-dot{background:var(--lime2);border-color:var(--lime2)}
    .safety{margin-top:auto;border:1px solid var(--line);border-radius:14px;padding:14px;background:var(--panel2)}.safety strong{font-size:12px}.safety p{font-size:11px;color:var(--muted);line-height:1.6;margin:8px 0 0}.online{display:inline-block;width:7px;height:7px;background:var(--lime2);border-radius:50%;margin-right:7px;box-shadow:0 0 10px rgba(100,117,65,.38)}
    main{padding:42px clamp(28px,5vw,76px) 70px;max-width:1240px;width:100%;margin:0 auto}.eyebrow{color:var(--lime);font-size:11px;letter-spacing:2px;font-weight:800}.hero{display:flex;justify-content:space-between;align-items:flex-start;gap:24px;margin-bottom:31px}.hero h2{font-size:clamp(30px,4vw,49px);line-height:1.1;letter-spacing:-1.8px;margin:10px 0 11px;max-width:690px}.hero p{color:var(--muted);margin:0;font-size:14px;line-height:1.7}.status-pill{border:1px solid var(--line);padding:9px 12px;border-radius:999px;color:#665c4d;font-size:11px;white-space:nowrap;background:rgba(255,250,242,.82)}
    .grid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(320px,.8fr);gap:18px}.card{background:linear-gradient(145deg,var(--panel),#fbf2e5);border:1px solid var(--line);border-radius:19px;box-shadow:var(--shadow)}.card-body{padding:24px}.card-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:19px}.card-title h3{margin:0;font-size:15px}.step-num{font-size:10px;color:var(--lime);border:1px solid rgba(111,121,70,.3);background:rgba(111,121,70,.07);border-radius:7px;padding:5px 7px;font-weight:800}
    label{display:block;color:#55493a;font-size:11px;font-weight:700;margin:0 0 8px}.field{margin-bottom:18px}.input-row{display:flex;gap:9px}.input,.textarea{width:100%;background:#fffdf8;border:1px solid #d7c7b4;color:var(--text);border-radius:11px;padding:12px 13px;outline:none;transition:.2s}.input:focus,.textarea:focus{border-color:#8d9760;box-shadow:0 0 0 3px rgba(111,121,70,.12)}.input[readonly]{background:#f1e7d8;color:#776a5b}.input::placeholder,.textarea::placeholder{color:#a49786}.textarea{min-height:143px;resize:vertical;line-height:1.6}.hint{color:#847563;font-size:11px;margin:7px 2px 0;line-height:1.5}.validation{margin-top:8px;font-size:11px;min-height:17px}.validation.good{color:var(--lime2)}.validation.bad{color:var(--red)}.provider-key{grid-column:1/-1;border:1px solid var(--line);background:var(--panel2);border-radius:10px;padding:10px 12px;margin-top:-2px}
    .btn{border:0;border-radius:11px;padding:12px 15px;cursor:pointer;font-weight:800;font-size:12px;transition:transform .15s,filter .15s,background .15s}.btn:hover{filter:brightness(.98);transform:translateY(-1px)}.btn:disabled{opacity:.45;cursor:not-allowed;transform:none}.btn-primary{background:var(--lime);color:#fffaf2}.btn-secondary{background:#eee4d5;color:#4b4033;border:1px solid #d9cbb8}.btn-ghost{background:#fffaf2;color:#746654;border:1px solid var(--line)}.launch{width:100%;padding:15px;font-size:13px;margin-top:5px}
    details{border-top:1px solid var(--line);margin-top:20px;padding-top:17px}summary{cursor:pointer;color:#675b4b;font-size:12px;font-weight:700;list-style:none}summary::-webkit-details-marker{display:none}.advanced{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:17px}.advanced .wide{grid-column:1/-1}.check-row{display:flex;gap:16px;flex-wrap:wrap;margin:18px 0}.check{display:flex;align-items:center;gap:8px;color:#675b4b;font-size:11px}.check input{accent-color:var(--lime)}
    .run-card{min-height:390px;display:flex;flex-direction:column}.empty{padding:48px 24px;text-align:center;margin:auto}.empty-icon{width:58px;height:58px;border:1px dashed #c5b59f;border-radius:18px;display:grid;place-items:center;margin:0 auto 16px;color:var(--lime);background:var(--panel2);font-size:23px}.empty h3{font-size:15px;margin:0 0 8px}.empty p{font-size:12px;color:var(--muted);line-height:1.65;margin:0}.run-view{display:none;padding:24px}.run-view.show{display:block}.run-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.run-head h3{margin:0 0 7px;font-size:16px}.run-head p{color:var(--muted);font-size:11px;margin:0;line-height:1.5;word-break:break-all}.badge{font-size:10px;font-weight:900;padding:7px 9px;border-radius:999px;background:rgba(79,111,117,.11);color:var(--blue)}.badge.success{background:rgba(100,117,65,.12);color:var(--lime2)}.badge.error{background:rgba(179,71,60,.1);color:var(--red)}
    .progress{height:5px;background:#e7dac8;border-radius:999px;overflow:hidden;margin:25px 0}.progress span{display:block;height:100%;background:linear-gradient(90deg,var(--lime2),#929b5e);border-radius:inherit;transition:width .4s}.progress .p0{width:7%}.progress .p1{width:17%}.progress .p2{width:34%}.progress .p3{width:50%}.progress .p4{width:67%}.progress .p5{width:84%}.progress .p6{width:100%}.result-box{border:1px solid var(--line);background:var(--panel2);border-radius:12px;padding:15px;margin-top:15px}.result-label{font-size:9px;color:#847563;font-weight:900;letter-spacing:1.4px}.result-text{font-size:12px;line-height:1.65;color:#4b4033;margin-top:7px;white-space:pre-wrap;word-break:break-word}.result-actions{display:flex;gap:9px;margin-top:18px}
    .modal{position:fixed;inset:0;background:rgba(56,44,31,.32);display:none;place-items:center;padding:20px;z-index:20;backdrop-filter:blur(10px)}.modal.show{display:grid}.modal-panel{width:min(680px,100%);max-height:78vh;background:var(--panel);border:1px solid var(--line);border-radius:20px;box-shadow:var(--shadow);display:flex;flex-direction:column}.modal-head{display:flex;align-items:center;justify-content:space-between;padding:20px;border-bottom:1px solid var(--line)}.modal-head h3{font-size:15px;margin:0}.close{background:none;border:0;color:#776a5b;font-size:20px;cursor:pointer}.crumb{padding:13px 20px;color:#7d6f5d;font-size:11px;border-bottom:1px solid var(--line);word-break:break-all}.folders{padding:9px;overflow:auto;min-height:260px}.folder{width:100%;display:flex;align-items:center;gap:11px;background:transparent;border:0;color:#4b4033;padding:11px;border-radius:9px;cursor:pointer;text-align:left}.folder:hover{background:#f1e7d8}.folder-icon{color:var(--amber)}.modal-foot{padding:15px 20px;border-top:1px solid var(--line);display:flex;justify-content:space-between;gap:10px}.toast{position:fixed;right:24px;bottom:24px;max-width:380px;background:var(--panel);border:1px solid var(--line);color:#4b4033;padding:13px 16px;border-radius:12px;box-shadow:var(--shadow);font-size:12px;display:none;z-index:30}.toast.show{display:block}.toast.error{border-color:#d59a8e;color:#91382f;background:#fff4ed}
    @media(max-width:900px){.app{grid-template-columns:1fr}.sidebar{display:none}.grid{grid-template-columns:1fr}main{padding:28px 18px 55px}.hero{display:block}.status-pill{display:inline-block;margin-top:18px}.advanced{grid-template-columns:1fr}.advanced .wide{grid-column:auto}}
  </style>
</head>
<body>
<div class="app">
  <aside class="sidebar">
    <div class="brand"><div class="mark">F</div><div><h1>ForgeMind</h1><p>Local Agent Workspace</p></div></div>
    <div class="side-label">AGENT PIPELINE</div>
    <div class="pipeline" id="pipeline">
      <div class="stage" data-stage="PLAN"><span class="stage-dot"></span>需求规划</div>
      <div class="stage" data-stage="ARCH"><span class="stage-dot"></span>架构设计</div>
      <div class="stage" data-stage="CODE"><span class="stage-dot"></span>代码实现</div>
      <div class="stage" data-stage="REVIEW"><span class="stage-dot"></span>代码审查</div>
      <div class="stage" data-stage="TEST"><span class="stage-dot"></span>测试验证</div>
      <div class="stage" data-stage="COMMIT"><span class="stage-dot"></span>Git 提交</div>
    </div>
    <div class="safety"><strong><span class="online"></span>本地安全模式</strong><p>只监听你的电脑。ForgeMind 创建独立分支，不会自动合并代码。</p></div>
  </aside>
  <main>
    <div class="hero"><div><div class="eyebrow">MULTI-AGENT CODING</div><h2>把需求交给团队，<br>让代码自己推进。</h2><p>选择一个项目，写下你想完成的事情。规划、开发、审查和测试由 ForgeMind 接力完成。</p></div><div class="status-pill"><span class="online"></span>本地服务已连接</div></div>
    <div class="grid">
      <section class="card"><div class="card-body">
        <div class="card-title"><h3>创建研发任务</h3><span class="step-num">NEW RUN</span></div>
        <form id="run-form">
          <div class="field"><label for="repo">项目文件夹</label><div class="input-row"><input class="input" id="repo" name="repo" placeholder="点击右侧按钮选择 Git 项目" required><button class="btn btn-secondary" type="button" id="browse">选择</button></div><div class="validation" id="repo-status">请选择一个已有 Git 提交且没有未保存修改的项目。</div><p class="hint">还没有项目？<button class="btn btn-ghost" type="button" id="demo">创建安全演示项目</button></p></div>
          <div class="field"><label for="requirement">你想让 ForgeMind 做什么？</label><textarea class="textarea" id="requirement" name="requirement" placeholder="例如：为这个项目增加健康检查接口，并补充自动化测试。" required></textarea></div>
          <details><summary>模型与运行设置</summary><div class="advanced">
            <div><label for="provider">模型供应商</label><select class="input" id="provider" required></select></div>
            <div><label for="model">模型名称（可输入筛选）</label><input class="input" id="model" list="model-options" autocomplete="off" placeholder="输入名称筛选模型" required><datalist id="model-options"></datalist></div>
            <div class="wide"><label for="base-url">API 地址</label><input class="input" id="base-url" type="url" required readonly></div>
            <div><label for="temperature">兼容温度</label><input class="input" id="temperature" type="number" min="0" max="2" step="0.01" placeholder="默认 0"></div>
            <div><label for="max-rework">最大返工次数</label><input class="input" id="max-rework" type="number" min="0" max="12" step="1" required><p class="hint">默认 6；保留安全上限，避免无限消耗。</p></div>
            <div class="provider-key"><div class="validation" id="key-status"></div><p class="hint" id="provider-hint"></p></div>
          </div><div class="check-row"><label class="check"><input id="structured" type="checkbox">严格结构化输出</label><label class="check"><input id="memory" type="checkbox">启用项目记忆</label><label class="check"><input id="approve" type="checkbox" checked>自动批准并提交</label></div></details>
          <button class="btn btn-primary launch" id="launch" type="submit">启动 Multi-Agent 研发任务</button>
        </form>
      </div></section>
      <section class="card run-card">
        <div class="empty" id="empty"><div class="empty-icon">↗</div><h3>等待新任务</h3><p>启动后，这里会展示当前阶段、分支和最终报告。<br>所有修改都留在独立分支中。</p></div>
        <div class="run-view" id="run-view"><div class="run-head"><div><h3 id="run-title">任务运行中</h3><p id="run-meta"></p></div><span class="badge" id="run-badge">RUNNING</span></div><div class="progress"><span class="p0" id="progress-bar"></span></div><div class="result-box"><div class="result-label">CURRENT OUTPUT</div><div class="result-text" id="run-output">正在准备项目工作区…</div></div><div class="result-actions"><button class="btn btn-secondary" id="report" type="button" disabled>查看完整报告</button></div></div>
      </section>
    </div>
  </main>
</div>
<div class="modal" id="folder-modal"><div class="modal-panel"><div class="modal-head"><h3>选择项目文件夹</h3><button class="close" id="close-modal" aria-label="关闭">×</button></div><div class="crumb" id="current-path"></div><div class="folders" id="folders"></div><div class="modal-foot"><button class="btn btn-ghost" id="go-parent" type="button">返回上一级</button><button class="btn btn-primary" id="select-current" type="button">选择当前文件夹</button></div></div></div>
<div class="toast" id="toast"></div>
<script nonce="forgemind-local">
  const byId=(id)=>document.getElementById(id);let currentDirectory="";let currentRunId=null;let pollTimer=null;let providers=[];
  async function api(url,options){const response=await fetch(url,{...options,headers:{"content-type":"application/json",...(options&&options.headers||{})}});const data=await response.json().catch(()=>({error:"服务返回了无法识别的结果"}));if(!response.ok)throw new Error(data.error||"操作失败");return data}
  function toast(message,error=false){const node=byId("toast");node.textContent=message;node.className="toast show"+(error?" error":"");setTimeout(()=>{node.className="toast"},4200)}
  function selectedProvider(){return providers.find((provider)=>provider.id===byId("provider").value)}
  function renderModelOptions(provider){const list=byId("model-options");list.replaceChildren();for(const model of provider.models){const option=document.createElement("option");option.value=model.id;option.label=model.label;list.append(option)}}
  function updateProviderStatus(provider){const status=byId("key-status");status.className="validation "+(provider.apiKeyConfigured?"good":"bad");status.textContent=provider.apiKeyConfigured?"✓ 后台密钥已配置（"+provider.apiKeyEnvironment+"）":"✕ 后台密钥未配置：请在 .env 填写 "+provider.apiKeyEnvironment+" 后重启";byId("provider-hint").textContent=provider.compatibility+"。模型框支持输入筛选，也可以手动填写供应商支持的其他模型名。"}
  function applyProvider(resetModel=true){const provider=selectedProvider();if(!provider)return;const custom=provider.id==="custom";byId("base-url").readOnly=!custom;byId("base-url").value=provider.baseUrl;renderModelOptions(provider);if(resetModel)byId("model").value=provider.defaultModel;byId("structured").checked=true;byId("temperature").value="0";updateProviderStatus(provider)}
  async function init(){try{const config=await api("/api/config");providers=config.providers;const select=byId("provider");select.replaceChildren();for(const provider of providers){const option=document.createElement("option");option.value=provider.id;option.textContent=provider.label;select.append(option)}select.value=config.providerId;const provider=selectedProvider();if(!provider)throw new Error("后台没有返回可用的模型供应商");byId("base-url").readOnly=provider.id!=="custom";byId("base-url").value=config.baseUrl;renderModelOptions(provider);byId("model").value=config.model||provider.defaultModel;byId("temperature").value=config.temperature===null?"":String(config.temperature);byId("max-rework").value=String(config.maxRework);byId("structured").checked=config.structuredOutput;currentDirectory=config.homeDirectory;updateProviderStatus(provider)}catch(error){toast(error.message,true)}}
  async function openFolder(path){try{const listing=await api("/api/directories?path="+encodeURIComponent(path||""));currentDirectory=listing.current;byId("current-path").textContent=listing.current;byId("go-parent").disabled=listing.parent===null;byId("go-parent").dataset.path=listing.parent||"";const folders=byId("folders");folders.replaceChildren();if(listing.entries.length===0){const empty=document.createElement("div");empty.className="hint";empty.textContent="这个文件夹里没有子文件夹";folders.append(empty)}for(const entry of listing.entries){const button=document.createElement("button");button.type="button";button.className="folder";button.innerHTML='<span class="folder-icon">▰</span><span></span>';button.lastElementChild.textContent=entry.name;button.addEventListener("click",()=>openFolder(entry.path));folders.append(button)}byId("folder-modal").classList.add("show")}catch(error){toast(error.message,true)}}
  async function inspectRepository(path){const status=byId("repo-status");status.className="validation";status.textContent="正在检查项目…";try{const result=await api("/api/repositories/inspect",{method:"POST",body:JSON.stringify({path})});byId("repo").value=result.root;status.className="validation good";status.textContent="✓ Git 项目可用 · 当前分支 "+result.branch;return true}catch(error){status.className="validation bad";status.textContent="✕ "+error.message;return false}}
  byId("browse").addEventListener("click",()=>openFolder(currentDirectory));byId("close-modal").addEventListener("click",()=>byId("folder-modal").classList.remove("show"));byId("folder-modal").addEventListener("click",(event)=>{if(event.target===byId("folder-modal"))byId("folder-modal").classList.remove("show")});byId("go-parent").addEventListener("click",()=>openFolder(byId("go-parent").dataset.path));byId("select-current").addEventListener("click",async()=>{byId("folder-modal").classList.remove("show");await inspectRepository(currentDirectory)});byId("repo").addEventListener("change",()=>inspectRepository(byId("repo").value));byId("provider").addEventListener("change",()=>applyProvider());
  byId("demo").addEventListener("click",async()=>{try{byId("demo").disabled=true;const result=await api("/api/demo-repository",{method:"POST",body:"{}"});await inspectRepository(result.path);toast("演示项目已准备好，可以直接填写需求")}catch(error){toast(error.message,true)}finally{byId("demo").disabled=false}});
  byId("run-form").addEventListener("submit",async(event)=>{event.preventDefault();const repoPath=byId("repo").value.trim();if(!await inspectRepository(repoPath))return;const temperature=byId("temperature").value.trim();const body={repoPath,requirement:byId("requirement").value,providerId:byId("provider").value,baseUrl:byId("base-url").value,model:byId("model").value,temperature:temperature===""?undefined:Number(temperature),maxRework:Number(byId("max-rework").value),structuredOutput:byId("structured").checked,memory:byId("memory").checked,approveAll:byId("approve").checked};try{byId("launch").disabled=true;const job=await api("/api/runs",{method:"POST",body:JSON.stringify(body)});currentRunId=job.id;showRun(job);pollTimer=setInterval(pollRun,1000);toast("任务已启动，页面可以保持打开")}catch(error){toast(error.message,true);byId("launch").disabled=false}});
  function showRun(job){byId("empty").classList.add("hidden");byId("run-view").classList.add("show");byId("run-meta").textContent=job.repoPath+" · "+job.id;const badge=byId("run-badge");badge.textContent=job.status;badge.className="badge"+(job.status==="SUCCEEDED"?" success":job.status==="RUNNING"?"":" error");byId("run-title").textContent=job.status==="RUNNING"?"Multi-Agent 团队正在工作":job.status==="SUCCEEDED"?"任务已完成":"任务未完成";byId("run-output").textContent=job.summary||stageMessage(job.stage);const completed=job.completedStages||[];const stages=[...document.querySelectorAll(".stage")];stages.forEach((node)=>{node.classList.toggle("done",completed.includes(node.dataset.stage));node.classList.toggle("active",job.stage===node.dataset.stage&&job.status==="RUNNING")});const progress=job.status==="SUCCEEDED"?6:Math.min(6,completed.length+(job.stage?1:0));byId("progress-bar").className="p"+progress;byId("report").disabled=!job.reportAvailable;byId("launch").disabled=job.status==="RUNNING"}
  function stageMessage(stage){const messages={PLAN:"正在理解需求并制定计划…",ARCH:"正在设计实现方案…",CODE:"正在编写和修改代码…",REVIEW:"正在进行独立代码审查…",TEST:"正在执行项目测试…",COMMIT:"正在创建安全的 Git 提交…"};return messages[stage]||"正在准备项目工作区…"}
  async function pollRun(){if(!currentRunId)return;try{const job=await api("/api/runs/"+encodeURIComponent(currentRunId));showRun(job);if(job.status!=="RUNNING"){clearInterval(pollTimer);pollTimer=null;toast(job.status==="SUCCEEDED"?"任务完成，代码已提交到独立分支":"任务结束，请查看错误信息",job.status!=="SUCCEEDED")}}catch(error){clearInterval(pollTimer);pollTimer=null;toast(error.message,true);byId("launch").disabled=false}}
  byId("report").addEventListener("click",()=>{if(currentRunId)window.open("/api/runs/"+encodeURIComponent(currentRunId)+"/report","_blank","noopener")});void init();
</script>
</body></html>`;
